---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.tekton.dev/release: devel
    version: v0.49.0
  name: tektonaddons.operator.tekton.dev
spec:
  group: operator.tekton.dev
  names:
    kind: TektonAddon
    listKind: TektonAddonList
    plural: tektonaddons
    singular: tektonaddon
  preserveUnknownFields: false
  scope: Cluster
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.version
          name: Version
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].status
          name: Ready
          type: string
        - jsonPath: .status.conditions[?(@.type=="Ready")].reason
          name: Reason
          type: string
      name: v1alpha1
      schema:
        openAPIV3Schema:
          description: Schema for the tektonaddons API
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}