{{- if .Values.serviceaccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-events-controller
  labels:
    app.kubernetes.io/component: events
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: tekton-pipelines
  {{- with .Values.serviceaccount.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
