apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tekton-operator.fullname" . }}-webhook
  namespace: {{ template "tekton-operator.namespace" . }}
  labels:
    {{- include "tekton-operator.labels" . | nindent 4 }}
    tekton: webhook
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tekton-operator.selectorLabels" . | nindent 6 }}
      tekton: webhook
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tekton-operator.labels" . | nindent 8 }}
        tekton: webhook
    spec:
      containers:
        - env:
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: CONFIG_LOGGING_NAME
              value: config-logging
            - name: WEBHOOK_SERVICE_NAME
              value: tekton-operator-webhook
            - name: WEBHOOK_SECRET_NAME
              value: tekton-operator-webhook-certs
          image: "{{ .Values.images.webhook.repository }}:{{ .Values.images.webhook.tag }}"
          name: webhook
          ports:
            - containerPort: 8443
              name: https-webhook
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}
      serviceAccountName: {{ include "tekton-operator.serviceAccountName" . }}
      {{- with .Values.webhook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
