apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tekton-operator.fullname" . }}
  namespace: {{ template "tekton-operator.namespace" . }}
  labels:
    {{- include "tekton-operator.labels" . | nindent 4 }}
    tekton: operator
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tekton-operator.selectorLabels" . | nindent 6 }}
      tekton: operator
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tekton-operator.labels" . | nindent 8 }}
        tekton: operator
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tekton-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: IMAGE_PIPELINES_PROXY
              value: "{{ .Values.images.proxy.repository }}:{{ .Values.images.proxy.tag }}"
            - name: IMAGE_JOB_PRUNER_TKN
              value: "{{ .Values.images.pruner.repository }}:{{ .Values.images.pruner.tag }}"
            - name: SYSTEM_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: tekton-operator
            - name: METRICS_DOMAIN
              value: tekton.dev/operator
            - name: CONFIG_OBSERVABILITY_NAME
              value: tekton-config-observability
            - name: AUTOINSTALL_COMPONENTS
              valueFrom:
                configMapKeyRef:
                  key: AUTOINSTALL_COMPONENTS
                  name: {{ include "tekton-operator.fullname" . }}-defaults
            - name: DEFAULT_TARGET_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  key: DEFAULT_TARGET_NAMESPACE
                  name: {{ include "tekton-operator.fullname" . }}-defaults
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.operator.repository }}:{{ .Values.images.operator.tag }}"
          imagePullPolicy: {{ .Values.images.operator.pullPolicy }}
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
      {{- with .Values.operator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
