apiVersion: v1
kind: Service
metadata:
  name: {{ include "tekton-operator.fullname" . }}-webhook
  namespace: {{ template "tekton-operator.namespace" . }}
  labels:
    {{- include "tekton-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8443
      protocol: TCP
      name: https-webhook
  selector:
    {{- include "tekton-operator.selectorLabels" . | nindent 4 }}
    tekton: webhook
