---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    {{- include "tekton-operator.labels" . | nindent 4 }}
  name: validation.webhook.operator.tekton.dev
webhooks:
  - admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        name: {{ include "tekton-operator.fullname" . }}-webhook
        namespace: {{ template "tekton-operator.namespace" . }}
    failurePolicy: Fail
    name: validation.webhook.operator.tekton.dev
    sideEffects: None