apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-pipelines-webhook
  labels:
    helmTemplateRemoveMe: |
      {{- with .Values.webhook.deployment.labels }}
        {{- toYaml . | nindent 4 }}
      {{- end}}
spec:
  template:
    metadata:
      labels:
        helmTemplateRemoveMe: |
          {{- with .Values.webhook.pod.labels }}
            {{- toYaml . | nindent 8 }}
          {{- end}}
    spec:
      affinity:
        helmTemplateRemoveMe: |
          {{- with .Values.webhookDeploymentTolerations.nodeAffinity }}
           {{- toYaml . |  nindent 8 }}
          {{- end }}
      containers:
      - name: webhook
        envFrom:
        - secretRef:
            name: "{{ .Values.webhook.envFromSecret }}"
            optional: true
      nodeSelector:
        helmTemplateRemoveMe: |
          {{- with .Values.webhookDeploymentTolerations.nodeSelector }}
            {{- toYaml . |  nindent 8 }}
          {{- end}}
      tolerations:
        - helmTemplateRemoveMe: |
            {{- with .Values.webhookDeploymentTolerations.tolerations }}
              {{- toYaml . |  nindent 6 }}
            {{- end}}
