name: Increment Chart Version

on: pull_request
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    
    steps:
      - name: check source code
        uses: actions/checkout@v3

      - name: next release version
        id: nextversion
        uses: jenkins-x-plugins/jx-release-version@v2.6.11
        with:
          previous-version: from-file:charts/tekton-pipeline/Chart.yaml

      - name: Update version in Chart.yaml
        id: updatechart
        uses: mikefarah/yq@v4.34.1
        with:
          cmd: yq eval '.version = "${{ steps.nextversion.outputs.version }}"' -i charts/tekton-pipeline/Chart.yaml

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update Chart.yaml'
