name: Increment Version

on: [pull_request, pull_request_target]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: check source code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.ACCESS_TOKEN }}
        

      - name: next release version
        id: nextversion
        uses: jenkins-x-plugins/jx-release-version@v2.6.11
        with:
          previous-version: from-file:charts/tekton-pipeline/Chart.yaml

      - name: Update version in Chart.yaml
        id: updatechart
        uses: mikefarah/yq@v4.34.1
        with:
          cmd: yq eval '.version = "${{ steps.nextversion.outputs.version }}"' -i charts/tekton-pipeline/Chart.yaml

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update Chart.yaml'
